---
config:
  theme: forest
---
gantt
    title Дорожная карта трансформации IT-ландшафта
    dateFormat YYYY-MM
    axisFormat %Y-%m
    
    section Фундамент и инфраструктура
    Облачная миграция инфраструктуры :2026-01, 4M
    Внедрение Kubernetes и IaC :2026-02, 3M
    Настройка CI/CD pipelines :2026-03, 2M
    Развертывание Kafka :2026-02, 3M
    
    section Платформа данных
    Миграция исторических данных в MinIO :2026-02, 6M
    Внедрение Apache Iceberg :2026-03, 4M
    Настройка DataHub каталога :2026-04, 3M
    Запуск Airflow оркестрации :2026-03, 2M
    
    section Портал самообслуживания
    Разработка семантического слоя (Cube.js) :2026-05, 4M
    Расширение для всех сотрудников :2026-07, 5M
    
    section Декомпозиция доменов
    Домен Клиентов (первый data product) :2026-03, 4M
    Финтех-домен (независимое развитие) :2026-05, 5M
    Медицинский домен (анонимизация) :2026-07, 6M
    Домен ИИ (MLOps платформа) :2026-08, 5M
    
    section Качество и безопасность
    Внедрение Data Quality мониторинга :2026-06, 3M
    Настройка гранулярного RBAC :2026-05, 4M
    Compliance аудит и мониторинг :2026-07, 4M
    Анонимизация медицинских данных :2026-08, 3M
    
    section Оптимизация и масштабирование
    Настройка FinOps для контроля затрат :2026-10, 3M
    Автомасштабирование платформы :2026-11, 3M
    Интеграция новых партнёров :2026-12, 4M
    Полное отключение legacy DWH :2027-03, 2M